##
# Makefile automatically generated by genmake 1.0, May-03-00
# genmake 1.0 by muquit@muquit.com, http://www.muquit.com/
# requires go-build-go, markdown-toc-go to build everything

PROGNAME := mailsend-go
GO_VERSION := 1.26
PROGNAME_WIN := $(PROGNAME).exe
PROGNAME_PI := $(PROGNAME)-raspberry-pi
PROGNAME_PI_JESSIE := $(PROGNAME)-raspberry-pi-jessie
DESTDIR=
VERSION := $(shell cat VERSION)
LDFLAGS := -ldflags "-w -s -X 'github.com/muquit/mailsend-go/pkg/version.Version=$(VERSION)'"
BUILD_OPTIONS := -trimpath
BINDIR= /usr/local/bin
MANPAGE= docs/mailsend-go.1
MANDIR= /usr/local/share/man/man1
CP= /bin/cp -v
OS= $(shell go env GOOS)
MTOC=markdown-toc-go
FORMULA_DIR=$(HOME)/gitdev/homebrew-formulae/Formula
FORMULA_FILE=$(FORMULA_DIR)/mailsend-go.rb

.PHONY: all build_all example gen usage dev mod_clean docs install install-bin \
        release brew check_github_token tidy clean help

all: build_all gen
	@echo "- Getting go get github.com/muquit/gomail@master ..."
	@echo "- Compiling ${PROGNAME} ..."
	go build $(BUILD_OPTIONS) $(LDFLAGS)
	/bin/ls -lt ${PROGNAME}

# use go-xbuild-go
build_all: native
	@echo "- Building for all selected platforms ..."
	/bin/rm -f bin/*
	go-xbuild-go -skip-brew -skip-brew-push -build-args '$(BUILD_OPTIONS) $(LDFLAGS)'
	@echo ""
	@echo "- Generating homebrew formula ..."
	$(MAKE) brew
	@echo ""

example:
	echo "Generating examples ..."
	@./scripts/mkexamples.sh

$(PROGNAME): native

# to strip out debug info: go build -ldflags="-s -w"

linux:
	@echo "- Building $(PROGNAME)_linux"
	@CGO_ENABLED=0 GOOS=linux go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME)_linux
	/bin/ls -lt $(PROGNAME)_linux
	@echo ""

native:
	@echo "- Building $(PROGNAME)"
	go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME)
	/bin/ls -lt $(PROGNAME)
	@echo ""

windows:
	@echo "- Building $(PROGNAME_WIN) for Windows amd64"
	CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME_WIN)
	/bin/ls -lt $(PROGNAME_WIN)
	@echo ""

mac:
	@echo "- Building $(PROGNAME) for Mac amd64"
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME)_mac
	/bin/ls -lt $(PROGNAME)_mac
	@echo ""

pi:
	@echo "- Building $(PROGNAME) for raspberry pi"
	GOOS=linux GOARCH=arm GOARM=7 go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME_PI)
	/bin/ls -lt $(PROGNAME_PI)
	@echo ""

pijessie:
	@echo "- Building $(PROGNAME) for raspberry pi jessie"
	GOARM=6 GOARCH=arm GOOS=linux go build $(BUILD_OPTIONS) $(LDFLAGS) -o $(PROGNAME_PI_JESSIE)
	/bin/ls -lt $(PROGNAME_PI_JESSIE)
	@echo ""

# generate files/examples.txt from docs/examples.md
# generate examples.go from examples.txt for -ex flag
gen: example usage docs

usage:
	echo "# Synopsis" > docs/usage.md
	echo '```' >> docs/usage.md
	@./mailsend-go -h >> docs/usage.md
	echo '```' >> docs/usage.md

dev: gen all doc

mod_clean:
	@./scripts/mod_clean.sh

docs:
	echo "Generating docs ..."
	$(MTOC) -i docs/main.md -o ./README.md  --glossary docs/glossary.txt --pre-toc-file docs/badges.md -f
	$(MTOC) -i docs/ChangeLog.md -o ./ChangeLog.md --glossary docs/glossary.txt -f -no-credit
	@./scripts/mk_man.sh

install: install-bin

install-bin:
	$(CP) $(PROGNAME) $(BINDIR)
	$(CP) $(MANPAGE) $(MANDIR)

release:
	go-xbuild-go --release \
		-skip-brew \
		-skip-brew-push

# create formula for homebrew
brew:
	./scripts/gen_homebrew_formula.rb \
		--desc "A CLI tool to send mail via SMTP protocol" \
		--output $(FORMULA_DIR)
	/bin/ls -lt $(FORMULA_FILE)
	@echo "*** Do not forget to check-in the formula!"

# check if GITHUB_TOKEN is valid
check_github_token:
	@curl -s -H "Authorization: token $(GITHUB_TOKEN)" \
		https://api.github.com/user | jq '{login, name, type}'
	@curl -sI -H "Authorization: token $(GITHUB_TOKEN)" \
		https://api.github.com/user | grep -i x-oauth-scopes

tidy:
	go mod tidy -go=$(GO_VERSION)

help:
	@echo "============================================================"
	@echo " make          - build binaries for various platforms"
	@echo "                 requires go-xbuild-go, markdown-toc-go"
	@echo "                 I use this target for creating distributions"
	@echo " make linux    - build linux client"
	@echo " make mac      - build mac client"
	@echo " make windows  - build 64 bit windows client"
	@echo " make release  - I use this to release using go-xbuild-go"
	@echo " make brew     - I use this to generate homebrew formula"
	@echo " make gen      - I use this to assemble README.md using markdown-toc-go"
	@echo " make clean"
	@echo "============================================================"

clean:
	/bin/rm -f $(PROGNAME) $(PROGNAME_WIN) $(PROGNAME)_$(OS) $(PROGNAME)_* *.bak \
		$(PROGNAME)_linux $(PROGNAME)_mac
